"""Your message here

Revision ID: c9ff14da3bf2
Revises: 
Create Date: 2024-12-21 03:13:20.469508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c9ff14da3bf2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_roles'), nullable=False),
    sa.Column('password_reset_token', sa.String(length=64), nullable=True),
    sa.Column('password_reset_expire', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_users_email'), 'service_users', ['email'], unique=True)
    op.create_index(op.f('ix_service_users_username'), 'service_users', ['username'], unique=True)
    op.create_table('sales_receipts',
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rest', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_auth_tokens',
    sa.Column('secret', sa.String(length=1024), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('token_type', sa.Enum('refresh', name='token_types'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_auth_tokens_secret'), 'service_auth_tokens', ['secret'], unique=True)
    op.create_table('service_logs',
    sa.Column('log_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_logs_created'), 'service_logs', ['created'], unique=False)
    op.create_index(op.f('ix_service_logs_log_type'), 'service_logs', ['log_type'], unique=False)
    op.create_table('payments',
    sa.Column('payment_type', sa.Enum('cash', 'card', name='paymenttype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['sales_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_receipt_products',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=0), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['sales_receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_receipt_products')
    op.drop_table('payments')
    op.drop_index(op.f('ix_service_logs_log_type'), table_name='service_logs')
    op.drop_index(op.f('ix_service_logs_created'), table_name='service_logs')
    op.drop_table('service_logs')
    op.drop_index(op.f('ix_service_auth_tokens_secret'), table_name='service_auth_tokens')
    op.drop_table('service_auth_tokens')
    op.drop_table('sales_receipts')
    op.drop_index(op.f('ix_service_users_username'), table_name='service_users')
    op.drop_index(op.f('ix_service_users_email'), table_name='service_users')
    op.drop_table('service_users')
    # ### end Alembic commands ###
